name: DC

on:
  push:
    branches: [ main ]

jobs: 
  bestHero: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: echo Batman Hello world

  justiceLeague:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Flash, Green Lantern, Superman and Wonderwoman
      
  joker:
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: windows-latest
    needs: [bestHero, justiceLeague]
    steps:
      - uses: actions/checkout@v2
      - run: |
            echo Ahoj Batmane
            echo Jsem vtipnej
